name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - name: Get Sources
        uses: actions/checkout@v2

      - name: Build Package
        run: swift build -v

      - name: Run tests
        run: swift test --enable-code-coverage -v
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with:
          xcode-version: "13.2"

      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/DucksPackageTests.xctest/Contents/MacOS/DucksPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: fail
          files: ./coverage_report.lcov
          verbose: true